name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        profile: [github.pr, gitlab.pr, git.fb, stash.pr, gerrit.cs]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: "zulu"
        java-version: "11"
    - name: Build with Maven
      run: mvn -B package --file pom.xml -P ${{ matrix.profile }}
